### ISSUE TITLE
Error: operations can apply to 2 objects in an array after an "add"

### ISSUE THREAD

**Issue by jacwright** [mohayonao/json-touch-patch#9]
When operations come after an "add" they affect both the newly added object as well as the one that was in its place.

This example:
```
patch({
  test: [
    { name: 'one' }
  ]
}, [
  { op: 'replace', path: '/test/0/name', value: 1},
  { op: 'add', path: '/test/0', value: { name: 'zero' }},
  { op: 'replace', path: '/test/0/name', value: 0 }
])
```

should have this result:
```
{
  test: [
    { name: 0 }
    { name: 1 }
  ]
}
```

but is resulting in this:
```
{
  test: [
    { name: 0 }
    { name: 0 }
  ]
}
```

**Comment by mohayonao** [comment]
I’ve checked this behavior.
This is a bug which caused by cache.
I’ll fix it, but may take a while.

**Comment by jacwright** [comment]
In the meantime, what do you think about removing the cache until it is fixed and publishing it to npm?
```js
// TODO use pluckWithCachedShallowCopy once fixed to account for changes to paths operations will make
var pluckFn = pluckWithShallowCopy;
```

Or you could use a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to determine if an object has already been copied and skip copying it, same as the cache but without having to watch paths.

**Comment by mohayonao** [comment]
I think your PR is perfect fix. Thanks!
